"""initial schema — all 12 tables

Revision ID: 0001
Revises:
Create Date: 2026-06-04

Hand-written (not autogenerated) so it is deterministic and reviewable. Mirrors
db/models.py exactly. Enum columns are emitted as VARCHAR + CHECK (native_enum=
False) to match the spec's hand-written DDL. gen_random_uuid() is core in PG13+.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _uuid_pk() -> sa.Column:
    return sa.Column(
        "id",
        postgresql.UUID(as_uuid=True),
        server_default=sa.text("gen_random_uuid()"),
        primary_key=True,
        nullable=False,
    )


def _created_at() -> sa.Column:
    return sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)


def _enum(*values: str, name: str) -> sa.Enum:
    # create_constraint=True is REQUIRED: in SQLAlchemy 2.0 a non-native Enum
    # defaults to create_constraint=False, which would emit a bare VARCHAR with
    # no DB-level enforcement. We want TEXT + CHECK(col IN (...)) per the spec.
    # `name` doubles as the CHECK constraint name (kept unique across tables).
    # length=32 matches db/models.py so create_all() (tests) and this migration
    # produce identically-sized columns, and the CHECK (not the length cap) is
    # what rejects out-of-vocabulary values.
    return sa.Enum(*values, name=name, native_enum=False, create_constraint=True, length=32)


def _conf() -> sa.CheckConstraint:
    # Fresh instance per table — a Constraint object binds to a single Table.
    return sa.CheckConstraint("confidence >= 0.0 AND confidence <= 1.0", name="confidence_range")


REVIEW = ("pending", "auto-approved", "human-approved", "rejected")


def upgrade() -> None:
    # --- regulations -------------------------------------------------------
    op.create_table(
        "regulations",
        _uuid_pk(),
        sa.Column("source_id", sa.Text(), nullable=False, unique=True),
        sa.Column("title", sa.Text()),
        sa.Column("jurisdiction", sa.Text()),
        sa.Column("document_type", sa.Text()),
        sa.Column("publication_date", sa.Date()),
        sa.Column("entry_into_force_date", sa.Date()),
        sa.Column("oj_reference", sa.Text()),
        sa.Column("file_path", sa.Text()),
        sa.Column(
            "ingestion_status",
            _enum("queued", "processing", "ingested", "stub", "failed", name="ingestion_status"),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("created_by", sa.Text()),
        sa.Column("metadata_hints", postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        _created_at(),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )

    # --- regulation_fields (EAV) ------------------------------------------
    op.create_table(
        "regulation_fields",
        _uuid_pk(),
        sa.Column("regulation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("regulations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("field_name", sa.Text(), nullable=False),
        sa.Column("value_text", sa.Text()),
        sa.Column("value_json", postgresql.JSONB()),
        sa.Column("reference", sa.Text()),
        sa.Column("confidence", sa.Float()),
        sa.Column("source_segment_index", sa.Integer()),
        sa.Column("extracted_by", sa.Text()),
        sa.Column("mapped_by", sa.Text()),
        sa.Column("validated_at", sa.DateTime(timezone=True)),
        sa.Column("review_status", _enum(*REVIEW, name="review_status_field"), server_default="pending", nullable=False),
        sa.Column("reviewer_note", sa.Text()),
        sa.Column("reviewer_id", sa.Text()),
        _created_at(),
        _conf(),
    )
    op.create_index("ix_regulation_fields_reg_field", "regulation_fields", ["regulation_id", "field_name"])

    # --- applicability_conditions -----------------------------------------
    op.create_table(
        "applicability_conditions",
        _uuid_pk(),
        sa.Column("regulation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("regulations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("parameter_name", sa.Text()),
        sa.Column("operator", _enum(">", "<", ">=", "<=", "==", "in", "not_in", "contains", name="operator")),
        sa.Column("value_min", sa.Float()),
        sa.Column("value_max", sa.Float()),
        sa.Column("value_enum", postgresql.JSONB()),
        sa.Column("value_bool", sa.Boolean()),
        sa.Column("unit", sa.Text()),
        sa.Column("condition_type", _enum("inclusion", "exclusion", name="condition_type"), nullable=False),
        sa.Column("is_structured", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("raw_text", sa.Text()),
        sa.Column("reference", sa.Text()),
        sa.Column("confidence", sa.Float()),
        sa.Column("review_status", _enum(*REVIEW, name="review_status_cond"), server_default="pending", nullable=False),
        _created_at(),
        _conf(),
    )
    op.create_index("ix_appl_cond_reg", "applicability_conditions", ["regulation_id"])
    op.create_index("ix_appl_cond_param", "applicability_conditions", ["parameter_name"])

    # --- hs_nomenclature ---------------------------------------------------
    op.create_table(
        "hs_nomenclature",
        _uuid_pk(),
        sa.Column("hs_code", sa.Text(), nullable=False, unique=True),
        sa.Column("description", sa.Text()),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("parent_code", sa.Text()),
        sa.Column("source", _enum("WCO", "EU_CN", name="hs_source"), nullable=False),
        _created_at(),
    )

    # --- hs_regulation_map -------------------------------------------------
    op.create_table(
        "hs_regulation_map",
        _uuid_pk(),
        sa.Column("hs_code", sa.Text(), nullable=False),
        sa.Column("regulation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("regulations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("confidence", sa.Float()),
        sa.Column("match_type", _enum("exact", "fuzzy", "manual", name="match_type"), nullable=False),
        sa.Column("review_status", _enum(*REVIEW, name="review_status_hs"), server_default="pending", nullable=False),
        sa.Column("reviewer_id", sa.Text()),
        _created_at(),
        _conf(),
        sa.UniqueConstraint("hs_code", "regulation_id", name="uq_hs_regulation"),
    )

    # --- regulation_relationships (typed edges) ----------------------------
    op.create_table(
        "regulation_relationships",
        _uuid_pk(),
        sa.Column("source_reg_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("regulations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("target_reg_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("regulations.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "relation_type",
            _enum("amends", "amended_by", "references", "supersedes", "superseded_by", "related", name="relation_type"),
            nullable=False,
        ),
        sa.Column("reference", sa.Text()),
        sa.Column("confidence", sa.Float()),
        sa.Column("source", _enum("text_extracted", "api_sourced", name="relation_source"), nullable=False),
        _created_at(),
        _conf(),
        sa.UniqueConstraint("source_reg_id", "target_reg_id", "relation_type", name="uq_relationship_edge"),
        sa.CheckConstraint("source_reg_id <> target_reg_id", name="no_self_edge"),
    )

    # --- certification_bodies + aliases -----------------------------------
    op.create_table(
        "certification_bodies",
        _uuid_pk(),
        sa.Column("canonical_name", sa.Text(), nullable=False, unique=True),
        sa.Column("body_type", _enum("notified", "accredited", "certified", name="body_type")),
        sa.Column("jurisdiction", sa.Text()),
        sa.Column("identifier", sa.Text()),
        _created_at(),
    )
    op.create_table(
        "certification_body_aliases",
        _uuid_pk(),
        sa.Column("alias", sa.Text(), nullable=False, unique=True),
        sa.Column("canonical_body_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("certification_bodies.id", ondelete="CASCADE"), nullable=False),
        _created_at(),
    )

    # --- jobs --------------------------------------------------------------
    op.create_table(
        "jobs",
        _uuid_pk(),
        sa.Column("file_path", sa.Text()),
        sa.Column("source_url", sa.Text()),
        sa.Column("source_id", sa.Text()),
        sa.Column("jurisdiction", sa.Text()),
        sa.Column("metadata_hints", postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("status", _enum("queued", "processing", "done", "failed", name="job_status"), server_default="queued", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True)),
        _created_at(),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_jobs_status", "jobs", ["status"])

    # --- job_errors --------------------------------------------------------
    op.create_table(
        "job_errors",
        _uuid_pk(),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("stage", sa.Text()),
        sa.Column("error_message", sa.Text()),
        sa.Column("traceback", sa.Text()),
        _created_at(),
    )

    # --- llm_audit_log -----------------------------------------------------
    op.create_table(
        "llm_audit_log",
        _uuid_pk(),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("jobs.id", ondelete="SET NULL")),
        sa.Column("agent", sa.Text()),
        sa.Column("model", sa.Text()),
        sa.Column("prompt", sa.Text()),
        sa.Column("response", sa.Text()),
        sa.Column("prompt_tokens", sa.Integer()),
        sa.Column("completion_tokens", sa.Integer()),
        sa.Column("latency_ms", sa.Integer()),
        _created_at(),
    )

    # --- product_attributes ------------------------------------------------
    op.create_table(
        "product_attributes",
        _uuid_pk(),
        sa.Column("attribute_name", sa.Text(), nullable=False, unique=True),
        sa.Column("unit", sa.Text()),
        sa.Column("value_type", _enum("range", "enum", "boolean", name="attribute_value_type"), nullable=False),
        sa.Column("enum_values", postgresql.JSONB()),
        sa.Column("added_by", sa.Text()),
        _created_at(),
    )


def downgrade() -> None:
    # Drop in reverse dependency order.
    op.drop_table("product_attributes")
    op.drop_table("llm_audit_log")
    op.drop_table("job_errors")
    op.drop_index("ix_jobs_status", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("certification_body_aliases")
    op.drop_table("certification_bodies")
    op.drop_table("regulation_relationships")
    op.drop_table("hs_regulation_map")
    op.drop_table("hs_nomenclature")
    op.drop_index("ix_appl_cond_param", table_name="applicability_conditions")
    op.drop_index("ix_appl_cond_reg", table_name="applicability_conditions")
    op.drop_table("applicability_conditions")
    op.drop_index("ix_regulation_fields_reg_field", table_name="regulation_fields")
    op.drop_table("regulation_fields")
    op.drop_table("regulations")
